In [1]:
import pandas as pd
data = {
    'Student':['Amit','Ravi','Sita','Priya','Rahul','Ajit'],
    'Hours_Studied': [2, 4, 6, 8, 10, 12],
    'Marks': [35,50,65,80,95,99]
}

df = pd.DataFrame(data)

df

  Student  Hours_Studied  Marks
0    Amit              2     35
1    Ravi              4     50
2    Sita              6     65
3   Priya              8     80
4   Rahul             10     95
5    Ajit             12     99

In [2]:
df.head(2)

  Student  Hours_Studied  Marks
0    Amit              2     35
1    Ravi              4     50

In [3]:
df.tail(2)

  Student  Hours_Studied  Marks
4   Rahul             10     95
5    Ajit             12     99

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        6 non-null      object
 1   Hours_Studied  6 non-null      int64
 2   Marks          6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [5]:
df.describe()

       Hours_Studied      Marks
count       6.000000   6.000000
mean        7.000000  70.666667
std         3.741657  25.350871
min         2.000000  35.000000
25%         4.500000  53.750000
50%         7.000000  72.500000
75%         9.500000  91.250000
max        12.000000  99.000000

In [6]:
df.columns

Index(['Student', 'Hours_Studied', 'Marks'], dtype='object')

In [7]:
df.dtypes

Student          object
Hours_Studied     int64
Marks             int64
dtype: object

In [8]:
df.sample(3)

  Student  Hours_Studied  Marks
2    Sita              6     65
0    Amit              2     35
5    Ajit             12     99

In [9]:
df.isnull().sum()

Student          0
Hours_Studied    0
Marks            0
dtype: int64

In [10]:
df['Student'].unique()

array(['Amit', 'Ravi', 'Sita', 'Priya', 'Rahul', 'Ajit'], dtype=object)

In [11]:
df.value_counts()

Student  Hours_Studied  Marks
Ajit     12             99       1
Amit     2              35       1
Priya    8              80       1
Rahul    10             95       1
Ravi     4              50       1
Sita     6              65       1
Name: count, dtype: int64

In [12]:
df['Marks'].value_counts()

Marks
35    1
50    1
65    1
80    1
95    1
99    1
Name: count, dtype: int64

In [13]:
df.corr(numeric_only=True)

               Hours_Studied     Marks
Hours_Studied       1.000000  0.990994
Marks               0.990994  1.000000

In [14]:
print(df["Marks"].max())
print(df["Marks"].min())
print(df["Marks"].mean())
print(df["Marks"].median())
print(df["Marks"].mode())
print(df["Marks"].std())
print(df["Marks"].var())

99
35
70.66666666666667
72.5
0    35
1    50
2    65
3    80
4    95
5    99
Name: Marks, dtype: int64
25.350871122442058
642.6666666666666